### ISSUE TITLE
Need English description/comments

### ISSUE THREAD

**Issue by sgladstone** [SPnl/nl.sp.bezorggebieden#1]
Can you update the info.xml to include English in the description and comment sections? Unfortunately I do not speak Dutch. (BTW: It would be great if this extension can be listed on http://civicrm.org/extensions )

**Comment by maevelevie** [comment]
This is an extension specifically developed for one customer that has no relevance outside the Netherlands whatsoever ;-).
The extensions that have been built for the SP that could be interesting to others are mostly on https://github.com/CiviCooP

**Comment by sgladstone** [comment]
I thought this report might be more generally useful due to the mention on the CiviCRM stack exchange ( http://civicrm.stackexchange.com/questions/2385/how-do-i-set-the-print-order-for-address-labels )

**Comment by maevelevie** [comment]
Ah, I see! I'll leave it to Jaap then to see whether this functionality is something we could document better / perhaps split into a separate extension.

**Comment by jaapjansma** [comment]
Hey Sarah,

As Kevin already told you this extension has a very specific purpose one small part of the extension to create address labels from a report but this is completly interwoven with the functionality of this extension. At stack exchange I pointed to this extension as an example but not meaning that this extension was ready to-go and a solution to the question asked.

Thanks for your message!
Jaap
